/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Buoi2.javaswing.b1;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author Dell
 */
public class SinhVIenForm extends javax.swing.JFrame {

    ArrayList<SinhVienHTTT> svhtttlist = new ArrayList<>();
    ArrayList<SinhVienMatMa> SvmmList = new ArrayList<>();
    /**
     * Creates new form Bai4
     */
    public SinhVIenForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btSinhVienHTTT = new javax.swing.JRadioButton();
        btSinhVIenMatMa = new javax.swing.JRadioButton();
        txtMASinhVien = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        cbGioiTinh = new javax.swing.JComboBox<>();
        txtDiemTrungBinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDonVi = new javax.swing.JTextField();
        TxtLuong = new javax.swing.JTextField();
        txtHocPhi = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        btLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên");

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        jLabel2.setText("Mã sinh viên ");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Ngày sinh: ");

        jLabel5.setText("Giới tính: ");

        jLabel6.setText("Diểm trùng bình: ");

        buttonGroup1.add(btSinhVienHTTT);
        btSinhVienHTTT.setText("Sinh viên HTTT");
        btSinhVienHTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSinhVienHTTTActionPerformed(evt);
            }
        });

        buttonGroup1.add(btSinhVIenMatMa);
        btSinhVIenMatMa.setText("Sinh viên mật mã");
        btSinhVIenMatMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSinhVIenMatMaActionPerformed(evt);
            }
        });

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Bông hông đáng yêu" }));
        cbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGioiTinhActionPerformed(evt);
            }
        });

        jLabel7.setText("Đơn vị: ");

        jLabel8.setText("Lương: ");

        jLabel9.setText("Học phí: ");

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btLuu.setText("Lưu");
        btLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btThem)
                        .addGap(91, 91, 91)
                        .addComponent(btLuu)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSinhVienHTTT)
                                .addGap(3, 3, 3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(btSinhVIenMatMa))
                            .addComponent(txtMASinhVien)
                            .addComponent(txtHoTen)
                            .addComponent(txtNgaySinh)
                            .addComponent(cbGioiTinh, 0, 258, Short.MAX_VALUE)
                            .addComponent(txtDiemTrungBinh)
                            .addComponent(txtDonVi)
                            .addComponent(TxtLuong)
                            .addComponent(txtHocPhi))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMASinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiemTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSinhVienHTTT)
                    .addComponent(btSinhVIenMatMa))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLuu)
                    .addComponent(btThem))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGioiTinhActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        String MSV = txtMASinhVien.getText();
        String HoTen = txtHoTen.getText();
        String NgaySInh = txtNgaySinh.getText();
        String GioiTinh = cbGioiTinh.getSelectedItem().toString();
        String DTB = txtDiemTrungBinh.getText();
       SinhVienMatMa SVMM;
       SinhVienHTTT SVHTTT;
       
       if(btSinhVienHTTT.isSelected()){
           double HocPhi = Double.valueOf(txtHocPhi.getText());
            //double HocPhi, String MaSinhVien, String HoTen, String NgaySInh, String DiemTrungBinh, String GioiTinh
            SinhVIen svhtt = new SinhVIen(HocPhi, MSV,HoTen, NgaySInh, DTB, GioiTinh);
            svhtttlist.add((SinhVienHTTT) svhtt);
            System.out.println(svhtttlist);
       }else if(btSinhVIenMatMa.isEnabled()){
           int luong = Integer.valueOf(TxtLuong.getText());
           String DonVi = txtDonVi.getText();
           //String DonVi, int Luong, String MaSinhVien, String HoTen, String NgaySInh, String DiemTrungBinh, String GioiTinh
           SinhVIen svmm =new SinhVienMatMa(DonVi, luong, MSV, HoTen, NgaySInh, DTB, GioiTinh);
           SvmmList.add((SinhVienMatMa) svmm);
           System.out.println(SvmmList);
       }
       
    }//GEN-LAST:event_btThemActionPerformed

    private void btSinhVienHTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSinhVienHTTTActionPerformed
        // TODO add your handling code here:
         txtDonVi.setEnabled(false);
        TxtLuong.setEnabled(false);
        txtHocPhi.setEnabled(true);
    }//GEN-LAST:event_btSinhVienHTTTActionPerformed

    private void btSinhVIenMatMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSinhVIenMatMaActionPerformed
        // TODO add your handling code here:
        txtDonVi.setEnabled(true);
        TxtLuong.setEnabled(true);
        txtHocPhi.setEnabled(false);
    }//GEN-LAST:event_btSinhVIenMatMaActionPerformed
    public void ghisvmm(ArrayList<SinhVienMatMa> list){
        try (PrintWriter pw = new PrintWriter(new File ("svmm.dat"))){
            for(SinhVienMatMa s : list){
                pw.println(s.getMaSinhVien());
                pw.println(s.getHoTen());
                pw.println(s.getNgaySInh());
                pw.println(s.getGioiTinh());
                pw.println(s.getDiemTrungBinh());
                pw.println(s.getDonVi());
                pw.println(s.getLuong());
            }
        } catch (Exception e) {
            System.out.println("got an exception!");
        }
    }
    public ArrayList docSvmm(){
        ArrayList<SinhVienMatMa> lits = new ArrayList<>();
        try (Scanner sc = new Scanner(new File("svmm.dat"))){
            while (sc.hasNext()) {
                SinhVienMatMa s = new SinhVienMatMa();
                s.setMaSinhVien(sc.nextLine());
                s.setHoTen(sc.nextLine());
                s.setNgaySInh(sc.nextLine());
                s.setGioiTinh(sc.nextLine());
                s.setDiemTrungBinh(sc.nextLine());
                s.setDonVi(sc.nextLine());
                s.setLuong(sc.nextInt());
                
                lits.add(s);
                
            }
            
        } catch (Exception e) {
            System.out.println("got an exception!");
        }
        return lits;
    }

    /**
     *
     * @param list
     */
    public void ghisvhttt(ArrayList<SinhVienHTTT> list){
        try (PrintWriter pw = new PrintWriter(new File ("svhttt.dat"))){
            for(SinhVienHTTT s : list){
                pw.println(s.getMaSinhVien());
                pw.println(s.getHoTen());
                pw.println(s.getNgaySInh());
                pw.println(s.getGioiTinh());
                pw.println(s.getDiemTrungBinh());
                pw.println(s.getHocPhi());
            }
        } catch (Exception e) {
            System.out.println("got an extieption!");
        }
        
    }
     public ArrayList docSvhtt(){
        ArrayList<SinhVienHTTT> lits = new ArrayList<>();
        try (Scanner sc = new Scanner(new File("svhtt.dat"))){
            while (sc.hasNext()) {
                SinhVienHTTT s = new SinhVienHTTT();
                s.setMaSinhVien(sc.nextLine());
                s.setHoTen(sc.nextLine());
                s.setNgaySInh(sc.nextLine());
                s.setGioiTinh(sc.nextLine());
                s.setDiemTrungBinh(sc.nextLine());
                s.setHocPhi(sc.nextLong());
                
                
                lits.add(s);
                
            }
            
        } catch (Exception e) {
            System.out.println("got an exception!");
        }
        return lits;
    }
    private void btLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLuuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVIenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVIenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVIenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVIenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVIenForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtLuong;
    private javax.swing.JButton btLuu;
    private javax.swing.JRadioButton btSinhVIenMatMa;
    private javax.swing.JRadioButton btSinhVienHTTT;
    private javax.swing.JButton btThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDiemTrungBinh;
    private javax.swing.JTextField txtDonVi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtMASinhVien;
    private javax.swing.JTextField txtNgaySinh;
    // End of variables declaration//GEN-END:variables
}
